name: Mic cheque one two
on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
jobs:

  build-python:
    runs-on: ubuntu-latest
    

    steps:
      - uses: actions/checkout@v2

      - name: Loading Python
        run: pip install pandas
